### ISSUE TITLE
Identity V3 and service catalog

### ISSUE THREAD

**Issue by einarf** [rackspace/gophercloud#407]
Got an issue with how the service catalog is fetched in identity v3. The current implementation is looking up endpoints by listing services and endpoints through `/services` and `/endpoints`. Not all providers give users access to do a `identity:service_list` or `identity:endpoint_list`, so this will not work for them.

There might be very good reasons for the current implementation, but why not just use the catalog returned in the token and/or query `/auth/catalog` to obtain it? As long as you are scoped to a domain and/or project, the catalog should always be present unless you specifically supply and opt-out query.

https://github.com/openstack/keystone-specs/blob/master/api/v3/identity-api-v3.rst

I ended up making a small package to override stuff for now. I'll gladly make a PR, but always better to discuss here first.

**Comment by ggiamarchi** [comment]
It's fun you ask that just now because i'am working on a fix for that. My work is quite done, a PR will arrive soon.

Actually, the current implementation is broken, not only because (as you said) the need to have the rights to access to `/services` and `/endpoints` but also because `/endpoints` does not returns real URLs but URL patterns. For instance, it will give for nova something like `http://nova.example.net:8774/v2/%(tenant_id)s/`. The real URL can only be retrieve from the service catalog.
